# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'
source 'https://github.com/combateafraude/iOS.git'
source 'https://cdn.cocoapods.org/'
target 'CafFaceAuthenticator' do
 # Comment the next line if you don't want to use dynamic frameworks
 use_frameworks!
 pod 'FaceAuth',  :path => '/Users/giovani.gambero/Documents/GitHub/react-native-caf-face-authenticator/ios/FaceAuthRN'
 # Pods for RnIos

end
